const data = [
  {
    id: "1",
    title: "Lindy Hop",
    start: "June",
    end: "August",
    lessons: "20 lessons",
    price: "450 €",
    reserved: 8,
    available: 6,
  },
  {
    id: "2",
    title: "Solo Jazz",
    start: "February",
    end: "April",
    lessons: "20 lessons",
    price: "400 €",
    reserved: 4,
    available: 11,
  },
  {
    id: "3",
    title: "Salsa",
    start: "May",
    end: "June",
    lessons: "15 lessons",
    price: "300 €",
    reserved: 13,
    available: 2,
  },
  {
    id: "4",
    title: "Ballet",
    start: "September",
    end: "December",
    lessons: "25 lessons",
    price: "600 €",
    reserved: 5,
    available: 5,
  },
  {
    id: "5",
    title: "Contemporary",
    start: "April",
    end: "September",
    lessons: "25 lessons",
    price: "550 €",
    reserved: 5,
    available: 9,
  },
];

export default data;
